version: "3.8"
services:
  node:
    container_name: nodefcl
    image: boymaas/nodefcl:f382dec_20211018_1839
    volumes:
      - "/home/ubuntu/base-path:/data"
      - "/home/ubuntu/:/config"
    ports:
      - "9944:9944"
      - "9933:9933"
      - "30333:30333"
    command: >
      --base-path /data
      --chain /config/fclMainnetSpecRaw.json
      --port 30333
      --rpc-port 9933
      --ws-port 9944
      --name "FCL authoring"
      --validator
      --rpc-cors=all
      --ws-max-connections 65536
      ${EXTRA_ARGS}
      --bootnodes /dns/boot.mainnet.fractalprotocol.com/tcp/30333/p2p/12D3KooWFQ9GLiqzsmfPtreuWheeZuJfacUVZEw2J7Mr3gYUWj9s
    restart: always
