[package]
name = "fractal_object_storage"
version = "0.1.0"
edition = "2021"

[dependencies]
blake2 = "0.10.4"
fallible-iterator = "0.2.0"
mockall_double = "0.2.1"
parity-scale-codec = "3.1.2"
parity-scale-codec-derive = "3.1.2"
thiserror = "1.0.30"

[dev-dependencies]
mockall = "0.11.0"
