[workspace]
members = [
  'blockchain/node',
  'blockchain/pallets/*',
  'blockchain/runtime',
  'object_storage',
  'support/*',
]

exclude = [
  'explorer',
  'support/@trustfractal',
  'support/node-production-aws-sns',
]
