[package]
name = "fractal_explorer"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "3.3.2"
anyhow = "1.0.51"
structopt = "0.3.25"

[[bin]]
name = "fractal_explorer_web"
path = "src/bin/web.rs"

[[bin]]
name = "fractal_explorer_index"
path = "src/bin/index.rs"
