web: ./target/release/fractal_explorer_web --port $PORT --postgres=$HEROKU_POSTGRESQL_AQUA_URL --redirect-https
indexing: ./target/release/fractal_explorer_index --postgres=$HEROKU_POSTGRESQL_AQUA_URL
ingest: node explorer/src/ingest.js --chain=wss://nodes.mainnet.fractalprotocol.com --postgres=$HEROKU_POSTGRESQL_AQUA_URL
