web: ./target/release/fractal_explorer_web --port $PORT
indexing: ./target/release/fractal_explorer_index
ingest: node explorer/src/ingest.js --chain=wss://nodes.mainnet.fractalprotocol.com --postgres=$HEROKU_POSTGRESQL_AQUA_URL
