name: Data Host Chrome Extension Build

on:
  push:
    branches:
      - master

  pull_request:
    types: [opened, synchronize]
    paths:
      - data_host/chrome_extension/**/*

jobs:
  build:
    runs-on: ubuntu-latest
    container: node:14.16.0
    defaults:
      run:
        working-directory: data_host/chrome_extension

    env:
      FORCE_COLOR: true

    steps:
      - uses: actions/checkout@v2

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install node dependencies
        run: yarn install

      - name: Build staging data host chrome extension
        run: yarn build

      - name: Upload staging artifact zip file
        uses: actions/upload-artifact@v2
        with:
          name: data-host-chrome-extension-staging
          path: data_host/chrome_extension/build
          if-no-files-found: error
