name: Pull Request

on:
  push:
    branches-ignore:
      - master
env:
  CARGO_TERM_COLOR: always

jobs:
  lints:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install latest nightly
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        profile: minimal
        override: true
        components: rustfmt, clippy

    - uses: Swatinem/rust-cache@v1

    # add a build stage, clippy fails on
    # the download stage for some reason
    - name: Download packages
      run: cargo fetch

    - name: Lint
      # run: cargo clippy --all-targets -- -D warnings
      run: cargo clippy -- -D warnings
    - name: Format
      run: cargo fmt -- --check

  verify:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install latest nightly
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        profile: minimal
        override: true
        target: wasm32-unknown-unknown

    - uses: Swatinem/rust-cache@v1

    - name: Run cargo check
      uses: actions-rs/cargo@v1
      with:
        command: check

    - name: Run tests
      run: cargo test --verbose
