name: Rust

on:
  push:
    branches: [ master, boymaas-cicd ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    # https://github.com/marketplace/actions/rust-toolchain
    - name: Install latest nightly
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        profile: minimal
        override: true
        target: wasm32-unknown-unknown
        components: rustfmt, clippy

    - uses: Swatinem/rust-cache@v1

    - name: Run cargo check
      uses: actions-rs/cargo@v1
      with:
        command: check


    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
